### ISSUE TITLE
key_up triggers SIGABRT on MacOS only in release mode

### ISSUE THREAD

**Issue by framp** [enigo-rs/enigo#103]
**Describe the bug**
When run in release mode on MacOS, key_up or key_down triggers a SIGABRT

```
test(84644,0x1178b6dc0) malloc: *** error for object 0x7fc05c406e90: pointer being freed was not allocated
test(84644,0x1178b6dc0) malloc: *** set a breakpoint in malloc_error_break to debug
fish: “cargo run --release --bin test” terminated by signal SIGABRT (Abort)
```

It works fine in debug mode

**To Reproduce**
```
use enigo::*;

fn main() {
    let mut enigo = Enigo::new();
    enigo.key_up(Key::Layout('e'));
}
```
Run in release mode `cargo run --release`

**Expected behavior**
Not crash, send a key_up event

**Environment (please complete the following information):**
 - OS: MacOS 10.15.7
 - Rust [e.g. rustc --version] 1.48
 - Library Version [e.g. enigo 0.0.13 or commit hash fa448be ] 5bb84e938009385987875472adafaa45613b3534

**Additional context**

**Comment by framp** [comment]
Anything higher than opt-level=0 triggers it

code here: https://github.com/enigo-rs/enigo/blob/master/src/macos/macos_impl.rs#L397

**Comment by pentamassiv** [comment]
Hi,
I recently became co-maintainer of this crate. I am sorry nobody responded to your issue earlier. I tried to reproduce it with the code from the master branch (not yet published), but for me everything worked as expected. Do you still have the issue? There have been a number of bug fixes since you reported the bug so I am not sure what exactly fixed it

**Comment by framp** [comment]
Hi @pentamassiv! Thanks for looking into it

I can't reproduce the issue anymore - I wonder if maybe it's been fixed in OSX itself


I don't remember exactly what I did about this problem (I was facing it when implementing https://github.com/framp/joystick-mapper a few years ago)


Regardless, thanks a lot and best of luck with the project

**Comment by pentamassiv** [comment]
Thanks, I'll do my best :-)
