### ISSUE TITLE
Why are there 20 millisecond sleeps in the macOS keyboard functions?

### ISSUE THREAD

**Issue by indianakernick** [enigo-rs/enigo#105]
I noticed a lot of latency and jitteriness. It turned out that `key_click` was taking 43 milliseconds to run! So I went to investigate and found that `key_click` sleeps for 20 milliseconds twice. See [here](https://github.com/enigo-rs/enigo/blob/5bb84e938009385987875472adafaa45613b3534/src/macos/macos_impl.rs#L369-L382).

Why is that the case? It's only the keyboard functions that do this and not the mouse functions. It seems unnecessary to me.

**Comment by Kerndog73** [comment]
I found out that the delays are there because it takes "a while" for modifier keys to take effect. So you need to wait a little bit after pressing shift before pressing 5 to get a %. I really can't stand the delay so I solved this by setting the flags on the key event.

This snippet will produce a keydown event with 5 (key code 23) and shift held down. So this will produce %. No annoying delay necessary.

```rust
let event = CGEvent::new_keyboard_event(self.event_source.clone(), 23, true).unwrap();
event.set_flags(CGEventFlags::CGEventFlagShift);
event.post(CGEventTapLocation::HID);
```

**Comment by xitanggg** [comment]
Thanks @indianakernick for digging into core graphics and sharing the very helpful snippet! I would make a small note that from observation, the flags are preserved so it might be helpful to reset it after use.

```rust
// Define CG key code for "5" key
// Reference: https://github.com/phracker/MacOSX-SDKs/blob/master/MacOSX10.13.sdk/System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/Headers/Events.h#L219
static _5_KEY_CODE: u16 = 0x17;

fn click_shift_5() {
    // Implementation reference: https://stackoverflow.com/questions/2008126/cgeventpost-possible-bug-when-simulating-keyboard-events

    // Event source state id reference: https://developer.apple.com/documentation/coregraphics/cgeventsourcestateid
    let event_source_state_id = CGEventSourceStateID::CombinedSessionState;
    let event_source = CGEventSource::new(event_source_state_id).unwrap();
    // Event tap location reference: https://developer.apple.com/documentation/coregraphics/cgeventtaplocation
    let event_tap_location = CGEventTapLocation::HID;

    let press_shift_5_event = CGEvent::new_keyboard_event(
        event_source.clone(),
        _5_KEY_CODE,
        true
    ).unwrap();
    press_shift_5_event.set_flags(CGEventFlags::CGEventFlagShift); // Set flags to Shift
    press_shift_5_event.post(event_tap_location);

    let release_5_event = CGEvent::new_keyboard_event(
        event_source.clone(),
        _5_KEY_CODE,
        false
    ).unwrap();
    release_5_event.set_flags(CGEventFlags::CGEventFlagNull); // Reset flags to null
    release_5_event.post(event_tap_location);

    // Release Shift Key for completeness. May or may not be necessary
    // given Apple's documentation is not clear on this.
    let release_shift_event = CGEvent::new_keyboard_event(
        event_source.clone(),
        KeyCode::SHIFT,
        false
    ).unwrap();
    release_shift_event.post(event_tap_location);
}

```

**Comment by pentamassiv** [comment]
Thank you both for the investigation. I never noticed that the sleeps are only needed for modifiers. I'll see if I can get rid of the sleep. It has been bothering me as well, but I don't have a mac. Now that the tests work in the CI, I feel more confident making changes on the other platforms without risking regressions.

**Comment by pentamassiv** [comment]
I can't reproduce your described behavior. I only commented out the sleep statements and then tried to run this code:

```
use enigo::{
    Direction::{Click, Press, Release},
    Enigo, Key, Keyboard, Settings,
};
use std::thread;
use std::time::Duration;

fn main() {
    env_logger::init();
    thread::sleep(Duration::from_secs(2));
    let mut enigo = Enigo::new(&Settings::default()).unwrap();

    enigo.key(Key::Unicode('a'), Click).unwrap();
    enigo.key(Key::Unicode('b'), Click).unwrap();
    enigo.key(Key::Unicode('c'), Click).unwrap();
    enigo.key(Key::Unicode('d'), Click).unwrap();
}
```

The output is "ab" and not the expected "abcd". It looks like not only modifiers require a sleep :/

**Comment by pentamassiv** [comment]
I noticed that another reason why sleep is needed. Apparently all events get ignored if the Enigo struct gets dropped before they were handled. I created a PR where the modifier flags get set manually and where the only sleep is in the Drop trait. Once it is thoroughly tested, we can hopefully get rid of almost all sleep on macOS :)
