### ISSUE TITLE
Add backward/forward mouse buttons

### ISSUE THREAD

**Issue by Yamakaky** [enigo-rs/enigo#110]
Windows: in https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-mouse_event, use `MOUSEEVENTF_XDOWN/DOWN` and `dwData`.

Linux: with xev, back seems to be code 8 and forward seems to be 9.

Mac: don't know, `CGMouseButton` only seems to support the three buttons.

**Comment by pentamassiv** [comment]
This was fixed a while ago. It is Linux and Windows only, since there seems to be no equivalent on macOS
