### ISSUE TITLE
Support linux via x11 without xdotools

### ISSUE THREAD

**Issue by lublak** [enigo-rs/enigo#112]
**Is your feature request related to a problem? Please describe.**

Currently x11 is supported only via xdotool.
There are a lib for x11: https://github.com/erlepereira/x11-rs with xtest and xlib
For waylands the wayland library in rust currently not support uinput.

**Describe the solution you'd like**
Support all os directly without any runtime dependencies.

**Describe alternatives you've considered**
runtime dependencie hell

**Comment by coderedart** [comment]
just wanted to mention that x11-rs has last commit on feb 2020 with last issue closed on sept 2020. 
OTOH, there's a much more actively maintained library https://github.com/psychon/x11rb which also has a comparison to other libraries https://github.com/psychon/x11rb/blob/master/doc/comparison.md .

**Comment by pentamassiv** [comment]
In case your are still interested in this, I created https://github.com/enigo-rs/enigo/pull/176 to make this possible. I used x11rb for it. Feel free to give it a try.

**Comment by lublak** [comment]
@pentamassiv oh! This project is alive?! :D
I will test it the next few days (but probably not until the weekend).
