### ISSUE TITLE
Wrong symbols

### ISSUE THREAD

**Issue by taep96** [enigo-rs/enigo#115]
**Describe the bug**
Trying to type Japanese symbols "やれやれ", results:
```
やれやれ
やれやれ
やややれ
やれやれ
やややや
やややや
やややれ
やややれ
```
Output is not correct most of the time.

**To Reproduce**
Source code:
```rs
use enigo::{Enigo, KeyboardControllable};
use tauri_hotkey::{Hotkey, HotkeyManager, Key, Modifier};
use std::{thread, time};

fn main() {
    let mut hkm = HotkeyManager::new();

    let mut enigo = Enigo::new();

    hkm.register(
        Hotkey {
            modifiers: vec![Modifier::ALT, Modifier::SHIFT],
            keys: vec![Key::A],
        },
        move || {
            println!("Alt-Shift-A pressed!");
            thread::sleep(time::Duration::from_millis(1000));
            enigo.key_sequence("やれやれ");
        },
    ).unwrap();

    loop {}
}
```

**Expected behavior**
Type correct symbols.

**Environment**
 - OS: Pop!_OS, xorg
 - Rust 1.57.0
 - Library Version `enigo = "0.0.14"`

**Comment by pentamassiv** [comment]
Hi,
I recently became co-maintainer of this crate. I am sorry nobody responded to your issue earlier. I tried to reproduce it, but for me everything worked as expected. I took your code and pressed the the buttons. For me the output was always the same. Do you still have the issue?

**Comment by taep96** [comment]
I switched the systems some time ago but I am still able to reproduce the issue, there's a delay until the symbols are typed as well.

**Comment by pentamassiv** [comment]
Is there a repo that I can check out or is the code exactly what you wrote above?
Do you mean the delay is longer than the one second pause from your code?
Which application are you trying to enter the text into?

When I keep the `ALT` key pressed, none of the symbols are typed. I am not sure where that limitation is coming from, but I don't thing it is something `Enigo` can change about that.
