### ISSUE TITLE
`Window` can be the wrong integer size?

### ISSUE THREAD

**Issue by elidupree** [enigo-rs/enigo#116]
I actually ran into this issue while using [Prunkton's fork](https://github.com/Prunkton/enigo), where it caused a segfault, but it seems like it would affect mainline Enigo as well.

[This source code from X11](https://code.woboq.org/qt5/include/X11/X.h.html) appears to make `XID`'s size (and hence `Window`'s size) conditional on some sort of built flags. I haven't fully grokked the flags, but what I do know is that *my* version of libxdo assumes that the Window type is 64 bits, while Enigo defines `type Window = c_int`, which is 32 bits.

I don't know why this isn't causing obvious bugs when calling `xdo_mouse_down`, etc., which pass a Window as an argument, but it seems like it would technically be a memory error (that might just coincidentally not cause the incorrect behavior during simple usage).

**Comment by pentamassiv** [comment]
Hmm, so sometimes it is 32 bits and sometime 64? Or did they switch to 64 bits in a newer version? I'll have to look into this

**Comment by FabioGNR** [comment]
I'm also running into this issue (with a crash as result).

From linked source code:
```
/*
 * _XSERVER64 must ONLY be defined when compiling X server sources on
 * systems where unsigned long is not 32 bits, must NOT be used in
 * client or library code.
 */
```
I couldn't find where this is set... however through another issue I found that the X11 bindings always use `c_ulong`:  
https://docs.rs/x11-dl/latest/i686-unknown-linux-gnu/x11_dl/xlib/type.XID.html

Looking for other usages I see that often it's based on the size of `unsigned long`:  
https://github.com/search?l=Meson&q=_XSERVER64&type=Code

So perhaps it should just be configured based on 32 vs 64 bits? Hope this info helps.

**Comment by pentamassiv** [comment]
The last link from FabisGNR is dead. I guess it now is: https://gitlab.freedesktop.org/xorg/xserver/-/blob/master/include/meson.build#L48

That was very helpful. If I understand correctly, using `c_ulong` should be fine. Depending on the architecture it then is either 32 or 64 bits long. 
[Here](https://rust-lang.github.io/libc/riscv32gc-unknown-linux-gnu/doc/libc/type.c_ulong.html) is an example where it is 32 bits and [here](https://rust-lang.github.io/libc/x86_64-unknown-linux-gnu/doc/libc/type.c_ulong.html) it is 64 bits

**Comment by pentamassiv** [comment]
This should now be fixed. I should have looked into it earlier :/
