### ISSUE TITLE
key_click triggers a segmentation fault when called with Key::Layout argument

### ISSUE THREAD

**Issue by cjiali** [enigo-rs/enigo#124]
**Describe the bug**
A segmentation fault is triggered when calling key_click function with a argument of type Key::Layout on MacOS.

**To Reproduce**
```rust
use enigo::{Enigo, Key, KeyboardControllable};
use std::thread;
use std::time::Duration;

fn main() {
    thread::sleep(Duration::from_secs(2));
    let mut enigo = Enigo::new();

    println!("1");
    enigo.key_down(Key::Meta);
    println!("2");
    enigo.key_click(enigo::Key::Layout('c'));
    println!("3");
    enigo.key_up(Key::Meta);
    println!("4");
}
```

Run with command `cargo run`, and will get an output as the following:

```shell
❯ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running `target/debug/enigo-debug`
1
2
zsh: segmentation fault  cargo run
```

**Expected behavior**
No crash, and send a key_click event.

**Environment (please complete the following information):**
 - OS: macOS Ventura 13.0.1 (22A400)
 - Rust: rustc 1.64.0 (a55dd71d5 2022-09-19)
 - Library Version: enigo 0.0.13

**Additional context**

**Comment by cjiali** [comment]
The issue is likely caused by getting the keyboard layout data failed, in this case,  the `TISGetInputSourceProperty` return `null`  and then `CFDataGetBytePtr` throw an `EXC_BAD_ACCESS` exception when calling `create_string_for_key`.

```
Exception has occurred.
EXC_BAD_ACCESS (code=1, address=0x0)
```

<img width="953" alt="image" src="https://user-images.githubusercontent.com/39233693/205479697-854fe949-56dd-4cd7-b540-1923e71725c4.png">

**Comment by pentamassiv** [comment]
Looks like a few other related projects also had this issue:
https://github.com/Narsil/rdev/pull/91
https://github.com/microsoft/vscode/issues/23833#issuecomment-291366154
https://github.com/microsoft/node-native-keymap/blob/089d802efd387df4dce1f0e31898c66e28b3f67f/src/keyboard_mac.mm#L87

**Comment by pentamassiv** [comment]
The PR was merged so it should be fixed now. Thank you
