### ISSUE TITLE
Add the "rust version" field to the Cargo.toml file

### ISSUE THREAD

**Issue by pentamassiv** [enigo-rs/enigo#127]
**Is your feature request related to a problem? Please describe.**
Some users might not keep their Rust versions up-to-date. It can be beneficial for them to easily see which version they at least have to run to be able to use the library.

**Describe the solution you'd like**
For this purpose there is the "rust version" field in the Cargo.toml file ([link](https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field)). When building with a version of Rust that is too old, the compiler will throw an error and inform the user about which version they at least have to run. We can run our Github Workflows with multiple versions of Rust so that we automatically detect it, if the version requirement is increased so it does not take a lot of effort to keep this updated. We can also add that information to the README.md file so that it is visible on crates.io too.

**Comment by pythoneer** [comment]
Good Idea! Is there an easy way to figure out which version that might be? I can try to make a "binary" search and just try it out.

**Comment by pythoneer** [comment]
Sounds like a good Point to start.
