### ISSUE TITLE
Allow serialization/deserialization of more things or remove the feature

### ISSUE THREAD

**Issue by pentamassiv** [enigo-rs/enigo#135]
**Is your feature request related to a problem? Please describe.**
There is an optional dependency for `serde` and `serde_derive` to serialize/serialize things from the library. If I am not mistaken, only `enum MouseButton` and  `enum Key` make any use of the dependency but that is not very useful. 

**Describe the solution you'd like**
We should think about either extending the usage or removing the feature. 

**Describe alternatives you've considered**
Leave it as it is

**Comment by pythoneer** [comment]
Not quite sure why we introduced that in the first place .. ah there ist the issue

https://github.com/enigo-rs/enigo/issues/31
