### ISSUE TITLE
Better define and document the DSL

### ISSUE THREAD

**Issue by pentamassiv** [enigo-rs/enigo#136]
**Describe the bug**
I believe the DSL and it's tokenize function need refinement and a refactor.

The function is hard to understand and the results are not what I would expect. For example we have the following test:

```
fn success() {
        assert_eq!(
            tokenize("{{Hello World!}} {+CTRL}hi{-CTRL}"),
            Ok(vec![
                Token::Sequence("{Hello World!} ".into()),
                Token::KeyDown(Key::Control),
                Token::Sequence("hi".into()),
                Token::KeyUp(Key::Control),
            ])
        );
}
```

I would not have expected the Token::Sequence("{Hello World!} ".into()) to be correct here.

In the dsl.rs example we do
`enigo.key_sequence_parse("{+UNICODE}{{Hello World!}} ❤️{-UNICODE}{+CTRL}a{-CTRL}");`
but the function returns `Err(UnknownTag("+UNICODE"))`. That is also not what we would want.

**Comment by pythoneer** [comment]
Yeah, i always wanted to use a library that would make it a little easier to create such a parser.
