### ISSUE TITLE
Can games detect this?

### ISSUE THREAD

**Issue by c9d5e1** [enigo-rs/enigo#139]
**Describe your Question**
A clear and concise description of what you want to know.

Will online games with anti-cheat detect this and think it's an autoclicker of some sort?

**Describe your Goal**
A clear and concise description of what you want to achieve. Consider the [XYProblem](http://xyproblem.info/)

I wish to create an undetectable macro.

**Environment (please complete the following information):**
 - OS: [e.g. Linux, Windows, macOS ..]
 - Rust [e.g. rustc --version]
 - Library Version [e.g. enigo 0.0.13 or commit hash fa448be ]
 - 
N/A

**Comment by pythoneer** [comment]
> Will online games with anti-cheat detect this and think it's an autoclicker of some sort?

No one can really answer this question other than the programmers of such anti-cheat tools. I am not very familiar with such tools but for all i know they can be very invasive. One way might be to hook *¹ into the necessary system API's and monitor them and there might be 100 others ways to do it and find "robotic" input based on heuristics that don't look human. 

*¹ https://learn.microsoft.com/en-us/windows/win32/winmsg/hooks

**Comment by BrettMayson** [comment]
Online like a website? No, but they may check for very small timings between keys/clicks. Native Windows games? Yes, they have the ability to. Some will act on it, some won't. If it is a concern I would advise against it. You will need to search for the policies of any games / anti-cheat software you are concerned about.
