### ISSUE TITLE
Sending keyboard input doesn't work

### ISSUE THREAD

**Issue by KentGrigo** [enigo-rs/enigo#140]
**Describe the bug**
Sending keyboard input doesn't work.

**To Reproduce**
I took the given example code and ran it with `cargo run`.
`main.rs`:
```
use enigo::{Enigo, MouseControllable, KeyboardControllable, MouseButton};

fn main() {
    let mut enigo = Enigo::new();
    enigo.mouse_move_to(500, 200);
    enigo.mouse_click(MouseButton::Left);
    enigo.key_sequence_parse("{+CTRL}a{-CTRL}{+SHIFT}Hello World{-SHIFT}");
}
```

`Cargo.toml`:
```
[package]
name = "test"
version = "0.1.0"
edition = "2021"

[dependencies]
enigo = "0.0.14"
```

**Expected behavior**
I expected that the mouse was clicked at position (500, 200) and then the text `HELLO WORLD` was written.

**Actual behavior**
The mouse position is correctly changed and the mouse is clicked.
But no text was written, instead I get the following output in the terminal:

```
PS C:\Personal\Path\Test> cargo run
   Compiling test v0.1.0 (C:\Personal\Path\Test)
    Finished dev [unoptimized + debuginfo] target(s) in 0.18s
     Running `target\debug\test.exe`
thread 'main' panicked at 'cannot transmute_copy if U is larger than T', /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\mem\mod.rs:1057:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\test.exe` (exit code: 101)
```

**Environment**
 - OS: Windows 11
 - Rust: rustc 1.65.0 (897e37553 2022-11-02)
 - Library Version: enigo 0.0.14

**Additional context**
I also tried:
- `key_click`
- `key_down`
- `key_sequence`

with no luck.

**Comment by a876691666** [comment]
Hello, I also have this problem

**Comment by BrettMayson** [comment]
This is an issue on Windows that is  fixed but not yet released. You can use this until a new release is made.
```toml
enigo = { git = "https://github.com/enigo-rs/enigo" }
```

**Comment by KentGrigo** [comment]
It works, thanks! ✨ 
Should we keep this issue open until the fix has been released?

**Comment by KentGrigo** [comment]
Ah! I just tested `key_click` and `key_down`.
The following program prints `8246` instead of moving the cursor up, down, left, and right.
```
use enigo::{Enigo, MouseControllable, KeyboardControllable, MouseButton};

fn main() {
    let mut enigo = Enigo::new();

    enigo.mouse_move_to(500, 225);
    enigo.mouse_click(MouseButton::Left);
    enigo.key_click(enigo::Key::UpArrow);
    enigo.key_click(enigo::Key::DownArrow);
    enigo.key_click(enigo::Key::LeftArrow);
    enigo.key_click(enigo::Key::RightArrow);
}
```

As for `key_down`, I tried the following program but it just prints `6`.
I'd at least have expected it to keep printing `6` instead of only doing so once.
```
use enigo::{Enigo, MouseControllable, KeyboardControllable, MouseButton};

fn main() {
    println!("Hello, world!");
    
    let mut enigo = Enigo::new();

    enigo.mouse_move_to(500, 225);
    enigo.mouse_click(MouseButton::Left);
    enigo.key_down(enigo::Key::RightArrow);
}
```

**Comment by KentGrigo** [comment]
I just tested `enigo.key_sequence_parse("{+RIGHTARROW}");` and it gives the same behavior: printing a `6` instead of moving the cursor.

**Comment by Megamannen** [comment]
I'm certain it's using wrong arrow keys (NumLock arrows)
And your NumLock state is in the number mode

**Comment by KentGrigo** [comment]
My keyboard is tenkeyless (TKL/80%), meaning that I don't have any of those buttons so I can't change the mode.

**Comment by KentGrigo** [comment]
I was hoping that I could use Enigo to change the mode for me by pressing the NumLock key but it's not supported.

**Comment by pentamassiv** [comment]
I guess we should add that functionality.

Right now we are still trying to improve the CI tests and get the PRs merged. We just started updating the crate a few weeks ago so we are not yet up to speed. In a few weeks we should be able to fix this error too.

**Comment by KentGrigo** [comment]
@Megamannen, after looking into it, I don't think that is the issue.
Based on the configuration in `src/win/keycodes.rs`:
```rust
pub const EVK_LEFT: u16 = 0x25;
pub const EVK_RIGHT: u16 = 0x27;
pub const EVK_UP: u16 = 0x26;
pub const EVK_DOWN: u16 = 0x28;
```
and the documentation in
https://msdn.microsoft.com/en-us/library/windows/desktop/dd375731 ,
I only see one option for each of the arrow keys:
- Left: `VK_LEFT | 0x25 | LEFT ARROW key`
- Up: `VK_UP | 0x26 | UP ARROW key`
- Right: `VK_RIGHT | 0x27 | RIGHT ARROW key`
- Down: `VK_DOWN | 0x28 | DOWN ARROW key`

and they all are set correctly.

The numpad values are something else entirely:
- Numpad 0: `VK_NUMPAD0 | 0x60 | Numeric keypad 0 key`
- Numpad 1: `VK_NUMPAD1 | 0x61 | Numeric keypad 1 key`
- Numpad 2: `VK_NUMPAD2 | 0x62 | Numeric keypad 2 key`
- Numpad 3: `VK_NUMPAD3 | 0x63 | Numeric keypad 3 key`
- Numpad 4: `VK_NUMPAD4 | 0x64 | Numeric keypad 4 key`
- Numpad 5: `VK_NUMPAD5 | 0x65 | Numeric keypad 5 key`
- Numpad 6: `VK_NUMPAD6 | 0x66 | Numeric keypad 6 key`
- Numpad 7: `VK_NUMPAD7 | 0x67 | Numeric keypad 7 key`
- Numpad 8: `VK_NUMPAD8 | 0x68 | Numeric keypad 8 key`
- Numpad 9: `VK_NUMPAD9 | 0x69 | Numeric keypad 9 key`

**Comment by KentGrigo** [comment]
@pentamassiv, that's completely fair. No pressure.
I'm just adding more information as I get them.

**Comment by Megamannen** [comment]
Now I remember fixing this issue in my own library, I can't look it up now, but I think you must set some flag also. My memory says it was called something like "EXT". But I might remember it incorrectly

**Comment by pentamassiv** [comment]
Seems like it is the same issue as this one here: https://github.com/enigo-rs/enigo/issues/99
There already is a PR (https://github.com/enigo-rs/enigo/pull/100), but it is outdated and cannot be merged. I'll update the PR and merge it soon.

**Comment by pentamassiv** [comment]
Fixed :)

**Comment by KentGrigo** [comment]
Thank you very much! 😄

**Comment by pentamassiv** [comment]
The new version was released :)
