### ISSUE TITLE
Run integration tests in the Github Workflows on all platforms

### ISSUE THREAD

**Issue by pentamassiv** [enigo-rs/enigo#141]
@BrettMayson had the idea to use a browser to run integration tests for the crate and laid the foundation for them. They run on Linux, but not on the other platforms. He said they succeed when ran locally. It would be nice if we could fix the tests so that we can run integration tests on all platforms automatically to get notified about regressions.

**Comment by pythoneer** [comment]
Has someone tried to run the windows test locally running inside a VM and not nativ under windows?

**Comment by pentamassiv** [comment]
In the Github Workflow on Windows I saw the following output:

```
     Running tests\browser.rs (target\debug\deps\browser-7ff64108df6d7934.exe)

running 1 test
Created channel
WebSocket server thread was spawned
TcpListener was created
Firefox is not installed
Try opening test page
[7020:1432:0210/174513.474:ERROR:edge_auth_errors.cc(484)] EDGE_IDENTITY: Get Default OS Account failed: Error: Primary Error: kImplicitSignInFailure, Secondary Error: kAccountProviderFetchError, Platform error: 0, Error string: 

[7020:1432:0210/174515.049:ERROR:fallback_task_provider.cc(124)] Every renderer should have at least one task provided by a primary task provider. If a "Renderer" fallback task is shown, it is a bug. If you have repro steps, please file a new bug and tag it as a dependency of crbug.com/739782.
[7020:1432:0210/174515.049:ERROR:fallback_task_provider.cc(124)] Every renderer should have at least one task provided by a primary task provider. If a "Renderer" fallback task is shown, it is a bug. If you have repro steps, please file a new bug and tag it as a dependency of crbug.com/739782.
New connection was made from 127.0.0.1:62438
Start waiting for messages
Start processing message
Message::Text received
msg: "open:"
Test page was opened
Done with launch function
Browser was launched
Move mouse
Executed Enigo
test browser_events has been running for over 60 seconds
Error: The operation was canceled.
```

On Mac, there were no errors. The test just timed out :(

**Comment by pentamassiv** [comment]
There is `xquartz` for Mac and cygwin has the packages `xorg-server xorg-server-extra` which contain xvfb so in theory it should be possible to use xvfb on all platforms but I tried that and failed. There just isn't any output that I can use to further debug it and that is nothing I am familiar with. Not sure if that is the correct path to continue trying.

Here is some code I had a look at to try to fix it:
https://github.com/tcltk/tk/blob/main/.github/workflows/mac-build.yml
https://github.com/tcltk/tk/blob/main/.github/workflows/win-build.yml
https://github.com/DrylandEcology/SOILWAT2/blob/a0816cbfe8fbc466e195799cf65087248303aa1b/.github/workflows/main_win.yml

**Comment by 107295472** [comment]
Why can't the mouse select pan?

**Comment by pentamassiv** [comment]
@Megamannen , in another issue you mentioned that you wrote a similar library. Were you able to run some integration tests for it?

**Comment by pentamassiv** [comment]
> Why can't the mouse select pan?

@107295472 I guess that was a mistake?

**Comment by 107295472** [comment]
found, you can select the translation。Is it faster than a robotgo of cgo

**Comment by pentamassiv** [comment]
> Has someone tried to run the windows test locally running inside a VM and not nativ under windows?

Yes, I just installed Windows 10 in Gnome Boxes and it works like a charm. It is a bit weird, because calling the functions to move the mouse work, but I don't see it move (I see new coordinates in the Firefox log when I use the "test page" though). I guess that is because the host controls the mouse and not the VM.

Also I installed [spice-guest-tools](https://www.spice-space.org/download.html) so that I can look at the Windows VM in fullscreen. That seems to mess with the mouse coordinates as well. The absolute ones are fine but the relative ones don't match the numbers I called the function with. The main_display_size() function returns the old dimensions of the "screen" before I installed spice. Maybe that is why they are weird.

**Comment by pentamassiv** [comment]
There is also https://github.com/sickcodes/Docker-OSX which apparently is able to use xvfb too

**Comment by pentamassiv** [comment]
I am trying to run the integration test on macOS. There is a popup that says that the code wants to control the computer using accessibility features. I have to grant access in the "Security & Privacy" preferences, located in System Preferences. That might be a reason why it does not work on macOS in the CI?

**Comment by pentamassiv** [comment]
The blocker for macOS is the missing accessibility permission. An explanation about the relevant DB can be found here: https://www.rainforestqa.com/blog/macos-tcc-db-deep-dive
Unfortunately it is protected by macOS's SIP so the DB is read-only. Therefore it currently is impossible to run the tests on macOS. :(

**Comment by pythoneer** [comment]
wow that is really unfortunate – do we have an alternative like a different CI we can run against?

**Comment by pythoneer** [comment]
maybe appveyor has SIP disabled in their images? https://github.com/appveyor/ci/issues/3426

**Comment by pentamassiv** [comment]
I created an issue and asked, if they could add the required permissions to the Github runner: https://github.com/actions/runner-images/issues/7269

**Comment by pythoneer** [comment]
Looks like [this PR](https://github.com/actions/runner-images/pull/7297) as merged.

**Comment by pentamassiv** [comment]
I tried adding more tests and to enable the integration tests on all platforms. My recent attempt can be found at https://github.com/pentamassiv/enigo/tree/more_test_cases. I am now at a point where moving the mouse and entering keys works. However the integration tests continue to fail under Windows and macOS. I added an action to take screenshots of the CI machine on all platforms. The screenshots are then uploaded as an artifacts so they can be looked at after the CI ran and we get more visibility into the machine.

One of the reasons it failed on Windows was that Edge was used and it opened the first-start page instead of the test page. Now I am trying to open Firefox manually, but for some reason that also does not work and I don't get why.

Maybe somebody else has an idea?

**Comment by pentamassiv** [comment]
We are so close to being able to run the integration tests in the CI...

**Comment by pentamassiv** [comment]
It is possible to run macOS in a VM by running the following two commands:
```
docker pull sickcodes/docker-osx:auto
docker run -it --net=host --device /dev/kvm -p 50922:10022 -v /tmp/.X11-unix:/tmp/.X11-unix -e "DISPLAY=${DISPLAY:-:0.0}" -e TERMS_OF_USE=i_agree -e GENERATE_UNIQUE=true sickcodes/docker-osx:auto
```
