### ISSUE TITLE
key_down crash with raw keys

### ISSUE THREAD

**Issue by NobodyForNothing** [enigo-rs/enigo#157]
**Describe the bug**
Using raw keys results in a 'not implemented' panic. This happens for key_down as well as for key_up. This is problematic, with keys that are not otherwise accessible.

**To Reproduce**
```use enigo::*;
fn main() {
  let mut enigo = Enigo::new();
  enigo.key_down(Key::Raw(0x38));
}
```

**Expected behavior**
Specified key should be pressed.

**Environment (please complete the following information):**

- OS: Linux Mint 20.3 x86_64
- Rust: rustc 1.67.1 (d5a82bbd2 2023-02-07)
- Library Version: enigo = "0.0.14"
- X11

**Additional context**

**Comment by pentamassiv** [comment]
Hi,
thank you for the report. We squashed a lot of bugs lately so I think this should be fixed by now. We just have not published a new version yet. Can you please try with the version from this repo? You can do that by adding the following snippet to your `Cargo.toml` file:

```
[dependencies]
enigo = { git = "https://github.com/enigo-rs/enigo" }
```

**Comment by NobodyForNothing** [comment]
The issue appears to be resolved in the github version.

**Comment by pentamassiv** [comment]
Okay, great! Thank you for checking it. A new version should be released within the next four weeks

**Comment by pentamassiv** [comment]
The new version was published :)
