### ISSUE TITLE
Wrong input on Mac 13.3

### ISSUE THREAD

**Issue by LeeeSe** [enigo-rs/enigo#169]
```rust
for key in keys_in_genshin {
        println!("should press:{key}, but enigo press:");
        enigo.key_click(enigo::Key::Layout(key));
        println!(" ");
    }
```
No matter what the value of key is, enigo always presses the A key.

the output is:
```
should press:d, but enigo press:

should press:n, but enigo press:
aa
should press:d, but enigo press:
a
```

**Comment by LeeeSe** [comment]
I don't know how to get the enigo logs to help you debug, if there is anything I can do please let me know

**Comment by pentamassiv** [comment]
Hi, thank you for bringing this to my attention. There is no need for you to do anything else. I can reproduce this myself and am now checking which commit broke it. I'll try to fix it today and publish a new version. Sorry about the inconvenience

**Comment by pentamassiv** [comment]
I had to revert 95e331b4d9ac6ed263a2f29a87dd8a9285087c66. A new version was released. Feel free to try it out

**Comment by LeeeSe** [comment]
Another question, I found that the speed of the keyboard emulation interface provided by MacSDK is low, it takes 45ms to emulate a keyboard input on M1 Mac Air, while the win32 interface only takes ns level to emulate a keyboard input, I have no experience, so please ask if there is any other way to achieve a lower latency to emulate a keyboard input.

**Comment by pentamassiv** [comment]
We intentionally sleep for a couple of ms as you can see [here](https://github.com/enigo-rs/enigo/blob/master/src/macos/macos_impl.rs#L362). Those sleeps are required on macOS for the key press to be registered. If they are pressed for too short, they are ignored. We do the same on Windows though (see [here](https://github.com/enigo-rs/enigo/blob/master/src/win/win_impl.rs#L232)), so I am a bit confused as to why it only takes ns on Windows for you. I'd like to get rid of these sleeps, but I am not aware of any way these sleeps can be avoided :(

**Comment by pentamassiv** [comment]
Does that work reliably without a sleep between the press and the release of the key or are keys ignored?
If it does, I'll use that instead and get rid of the delay.

**Comment by LeeeSe** [comment]
I simply tested it on the Windows platform, but not on buttons like Control, and the results seem to be fine, you can find the code here[key_test](https://github.com/LeeeSe/key_speed_test)

The test results are as follows:
```shell
PS C:\Users\Administrator\code\key_speed_test> cargo run
   Compiling key_speed_test v0.1.0 (C:\Users\Administrator\code\key_speed_test)
    Finished dev [unoptimized + debuginfo] target(s) in 0.68s
     Running `target\debug\key_speed_test.exe`
Press 36 keys in 4.7608ms
PS C:\Users\Administrator\code\key_speed_test> abcdefghijklmnopqrstuvwxyz0123456789
```

**Comment by LeeeSe** [comment]
Sorry, I made a mistake, it should be μs instead of ns

**Comment by pentamassiv** [comment]
Enigo no longer needs any sleeps on Windows anymore. They are still there on macOS though
