### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by chongqiangchen** [enigo-rs/enigo#170]
**Describe the bug**
error: failed to select a version for the requirement `windows = "^0.47"`
candidate versions found which didn't match: 0.48.0, 0.46.0, 0.44.0, ...
location searched: crates.io index
required by package `enigo v0.1.1 (https://github.com/enigo-rs/enigo#76cd7132)`
    ... which satisfies git dependency `enigo` of package `app v0.1.0 (/Users/xxxxx/ideas/xxxx/src-tauri)`
       Error failed to build app: failed to build app
 ELIFECYCLE  Command failed with exit code 1.

**To Reproduce**
in tauri project: cargo update

**Expected behavior**

**Environment (please complete the following information):**

- OS: [macOS ..]
- Rust [rustc 1.68.2 (9eb3afe9e 2023-03-27)]
- Library Version [76cd7132]

**Comment by pentamassiv** [comment]
The new version is online.

BTW: You mentioned that you are using enigo in a tauri project. Does it work for you? There is a known issue with tauri https://github.com/enigo-rs/enigo/issues/153.

**Comment by chongqiangchen** [comment]
thx
