### ISSUE TITLE
Enigo could work with programs that use DirectX/DirectInput

### ISSUE THREAD

**Issue by Multirious** [enigo-rs/enigo#172]
**Is your feature request related to a problem? Please describe.**
I want to simulate mouse input, specifically the movement to a game that uses DirectInput but Enigo doesn't work.

**Describe the solution you'd like**
Use `windows::Win32::UI::Input::KeyboardAndMouse::MOUSEEVENTF_MOVE` which seems to "work" for my case.

**Describe alternatives you've considered**
I have created a crate for this which are not far too different from Enigo's implementation. (In the back end)

**Comment by pentamassiv** [comment]
Thanks for the tip, I will check it out

**Comment by Multirious** [comment]
Also, the simulated mouse move is a bit weird.
I have a work around where I used `SetCursorPos` to move the mouse to my expected position and use this `MOUSEEVENTF` to move x by -1 and 1 so the game actually detect the mouse input in the right position.

I haven't do things around with keyboard input.

**Comment by Iamhere345** [comment]
Has anyone investigated this yet? DirectInput support would be extremely helpful.

**Comment by Multirious** [comment]
@Iamhere345 and any other people that want a simple script to make this work quick;
You can take a look at my little code [here](https://github.com/kemuler/kemuler-windows/blob/main/src/inner.rs).
Significant function you should find is `mouse_move_to` (and any other variant of it) should work.
You have to modify it a little bit because it's part of a project I'm working on, [`kemuler`](https://github.com/kemuler).
If you have the time, you could also check that out!

**Comment by Multirious** [comment]
I wonder how AutoHotKey and AutoIt did it. I've tested my above code and the method isn't good enough. There are still some game that is still doesn't want to detect the input.

**Comment by pentamassiv** [comment]
I personally don't use Windows so I don't play any games on it. Could you tell me, which games did not work without using `MOUSEEVENTF_MOVE`, which games started working when using it and which games still do not work? Preferably free games/programs so that I can test them myself in a VM.

**Comment by pentamassiv** [comment]
Can you give it a try and confirm if the issue was fixed for you?
