### ISSUE TITLE
Do not panic when `SetCursorPos` fails

### ISSUE THREAD

**Issue by chengyuhui** [enigo-rs/enigo#177]
**Describe the bug**
Based on my own testing, the `SetCursorPos` API does fail occasionally when I call `mouse_move_relative`, especially on low-end system that is under load.

**To Reproduce**
Call `mouse_move_relative` with really high frequency (e.g. when mirroring high precision and frequency mouse movements from other system) on a low-end system.

**Expected behavior**
At least do not panic when the API call fails.

`mouse_move_relative` should really feed the relative movements to the system directly with `SendInput`, instead of converting them to absolute positions.

**Environment (please complete the following information):**

- OS: Windows 10
- Rust: rustc 1.69.0 (84c898d65 2023-04-16)
- Library Version: 0.1.2

**Additional context**
N/A

**Comment by chengyuhui** [comment]
Also #172, we should really try to use `SendInput` for all mouse movement events.

**Comment by pentamassiv** [comment]
Thanks for the report. I will be traveling until the end of the month and won't have time to have a look at this until then.

**Comment by chengyuhui** [comment]
It's fine since I have temporarily moved to using `SendInput` on Windows, as I kept triggering this panic on a remote control application that I wrote for daily use, and crashing of the application means that I lose control to one of my machines.

However, relative inputs generated by `SendInput` is subject to pointer acceleration on Windows, which might not be desirable.

**Comment by chengyuhui** [comment]
After investigation, I have found out that Windows by default prevents the application to move the mouse if an elevated window is currently in focus (this is called UIPI). In this case `SetCursorPos` will return an error.

Panicking in this case means that the application will crash every time an elevated window (e.g. task manager) is focused.

**Comment by pentamassiv** [comment]
Fixed
