### ISSUE TITLE
How to extend window size by dragging window boundaries

### ISSUE THREAD

**Issue by xfengw** [enigo-rs/enigo#189]
**Describe your Question**
How to extend window size by dragging window boundaries

**Describe your Goal**
I operated Windows remotely, moved the mouse to the edge of a window, and found that I could not hover, and I could not expand the window size with the mouse.

**Environment (please complete the following information):**
windows11
- OS: [e.g. Linux, Windows, macOS ..]
- Rust [e.g. rustc --version]
- Library Version [e.g. enigo 0.0.13 or commit hash fa448be ]

**Comment by pentamassiv** [comment]
Thank you for the report. I'll have to look into that to see if it somehow is possible

**Comment by pentamassiv** [comment]
I can't reproduce this with the current code on the master branch. I did not use a remote machine, but I ran the following code in a VM with Windows installed:

```
use enigo::{Enigo, MouseButton, MouseControllable};
use std::thread;
use std::time::Duration;

fn main() {
    let wait_time = Duration::from_secs(2);
    let mut enigo = Enigo::new();

    thread::sleep(Duration::from_secs(4));
    println!("screen dimensions: {:?}", enigo.main_display_size());
    println!("mouse location: {:?}", enigo.mouse_location());

    thread::sleep(wait_time);

    enigo.mouse_down(MouseButton::Left);
    thread::sleep(wait_time);

    enigo.mouse_move_relative(100, 100);
    thread::sleep(wait_time);

    enigo.mouse_up(MouseButton::Left);
}
```

I ran the code and quickly moved the mouse to the edge of a window. Then I waited for the program to run. It successfully resized the window.

Can you try again and see if you still have issues with it?

**Comment by pentamassiv** [comment]
I assume it is not an issue anymore. Feel free to reopen it, if it is
