### ISSUE TITLE
[Feature request] Allow listening to keyboard input and replacing it with something else

### ISSUE THREAD

**Issue by okrightall** [enigo-rs/enigo#190]
[Feature request] Implement
     1.shortcut key call function names for combination keys, e.g: addHotkey(["CtrllLeft", "Altleft","d"],foo)     
                                                                                                 fn foo() {println!("Hello World!");}
    2.Hotstrings:addHotstring("aa" ,  "Hello World!");
                        addHotstring("cc ", "Hello!");‘

**Comment by pentamassiv** [comment]
Sorry, but I don't understand. Please explain your feature request

**Comment by okrightall** [comment]
The function implemented by this create is similar to the keyboard module in Python or the corresponding functions in the autohotkey language

**Comment by okrightall** [comment]
Like this:https://pypi.org/project/keyboard/
import keyboard
keyboard.add_hotkey('ctrl+shift+a', print)

# Blocks until you press esc.
keyboard.wait('esc')

# Type @@ then press space to replace with abbreviation.
keyboard.add_abbreviation('@@', 'my.long.email@example.com')

**Comment by pentamassiv** [comment]
Okay, I think I now understood.

That is currently out of the scope of this library. It can only simulate input. It cannot listen to input. In order for the described feature to work, you would have to be able to listen (and suppress) input.
