### ISSUE TITLE
Is it possible to get mouse move without actually moving the cursor?

### ISSUE THREAD

**Issue by HuakunShen** [enigo-rs/enigo#192]
**Describe your Question**
I am wondering if it's possible to detect mouse move but don't move the cursor, or hide the cursor somehow.

**Describe your Goal**
For example, if I want to build a remote desktop controlling app, how to detect mouse movements and replect on the remote computer without actually messing up the controller computer.

**Environment (please complete the following information):**

- OS: [Linux, Windows, macOS]
- Rust 1.68.2
- Library Version 0.1.2

**Comment by pentamassiv** [comment]
I am not sure I understand you correctly.

You can just check where the cursor is with https://docs.rs/enigo/0.1.2/enigo/trait.MouseControllable.html#tymethod.mouse_location. If you call that twice, you can see if there is a difference. So something like this:
```
use enigo::{Enigo, MouseControllable};
use std::thread;
use std::time::Duration;

fn main() {
    let wait_time = Duration::from_secs(2);
    let enigo = Enigo::new();

    println!("mouse location: {:?}", enigo.mouse_location());
    thread::sleep(wait_time);
    println!("mouse location: {:?}", enigo.mouse_location());
}
```

If you want to get notified immediately with each move (similar to a keylogger), then the answer is no. That is out of the scope of this library. It does not listen to key presses or mouse moves.

**Comment by HuakunShen** [comment]
@pentamassiv I don't think you understood my question. Consider the example scenario (remote desktop) I gave. I want to detect mouse movement without actually moving the cursor on the host. The cursor virutally belongs to the remote computer.

**Comment by pentamassiv** [comment]
Yes, on the remote machine, you would call `enigo.mouse_location() `

**Comment by HuakunShen** [comment]
But when I move the mouse on the host machine, I don't want the mouse to move. Otherwise clicking not only happens on remote, but also on the host machine; and when the cursor reaches the edge of the host machine, it will be unable to move on the remote machine.

**Comment by pentamassiv** [comment]
Okay, now I understand. You want to build an application that captures your mouse moves, clicks and whatever you typed and sends it to the remote machine. Only there your actions would take effect.

enigo is not capable of detecting anything input related (except for the current mouse location). You can use it on the remote machine to simulate the input from the host, but you cannot use it for what you planned on the host. That is unfortunately out of the scope of this library
