### ISSUE TITLE
Thread sleep in MacOs impl KeyboardControllable

### ISSUE THREAD

**Issue by wutterfly** [enigo-rs/enigo#193]
**Describe the bug**
The MacOs implementation for  KeyboardControllable contains delays with 20 Milliseconds.  In the implementation for Windows there are no delays.

enigo/src/macos/macos_impl.rs:
- line 374
- line 382

**Expected behavior**
KeyUps and KeyDowns should not have any delay. I don't think these delays are necessary for functionality.

In the Documentation for KeyClick (MacOs and Windows impl)  it should be documented, that there is a 20 Millisecond delay between KeyDown and KeyUp.

**Comment by pentamassiv** [comment]
Unfortunately they are needed. See https://github.com/enigo-rs/enigo/issues/105
