### ISSUE TITLE
Windows 10: ENTER/RETURN key does not get typed when called  enigo.key_sequence(data_string);

### ISSUE THREAD

**Issue by asifashraftcp** [enigo-rs/enigo#199]
**Describe the bug**
I send this text from tauri to rust backend. On windows 10. The Enter/Return key does not get printed.  All the following variable gets written on a single line.

const testText = `
❤️
ABCDEFGHIJKLMNOPQRSTUVWXYZ
abcdefghijklmnopqrstuvwxyz
\`1234567890-=
~!@#$%^&*()_+
[]\\;',./{}|:"<>? before tab  after tab  two  spaces
`;

**To Reproduce**
On windows 10 send RETURN key via  enigo.key_sequence(data_string);

**Expected behavior**
Return key should be typed even using windows 10

**Environment (please complete the following information):**

- OS: Windows 10
- Rustrustc 1.71.1 (eb26296b5 2023-08-03)
- Library Version enigo = "0.1.2"

**Comment by aaron404** [comment]
I'm seeing the same problem on win 11. It depends on the target I am sending keys to though, for example it works sending keys to notepad but not to some games. The normal printable characters work in game though.

**Comment by pentamassiv** [comment]
Should be fixed now on master
