### ISSUE TITLE
Use streams :D

### ISSUE THREAD

**Issue by legolord208** [enigo-rs/enigo#20]
In the Gitter chat, me and @pythoneer (lead dev) decided using streams for this would be cool.

Imagine something like this: `write!(enigo::out, "{}h{}ello {}w{}orld", enigo::shift_on, enigo::shift_off, enigo::shift_on, enigo::shift_off)`

**Comment by legolord208** [comment]
See [![the branch](http://i.imgur.com/ZwD879T.png)streams](https://github.com/enigo-rs/enigo/tree/streams)

**Comment by legolord208** [comment]
This was a bad idea

**Comment by pythoneer** [comment]
no it was not! I foresee it's coming back in the future ... mind my words 😄
