### ISSUE TITLE
Scroll lock

### ISSUE THREAD

**Issue by Aworldc** [enigo-rs/enigo#214]
**Is your feature request related to a problem? Please describe.**
It looks like you can't press the scroll lock key. This is an issue for one of my projects, where i need to be able to automatically press the scroll lock key.

**Describe the solution you'd like**
Support for pressing the scroll lock key, and a dsl tag for it. (this project decodes key sequences from a config file with the dsl)

**Additional context**
I'm on linux/X11. I've verified that linux supports it (at least in libreoffice calc).

This is the output of `xmodmap -pm` incase it helps:
```
shift       Shift_L (0x32),  Shift_R (0x3e)
lock        Caps_Lock (0x42)
control     Control_L (0x25),  Control_R (0x69)
mod1        Alt_L (0x40),  Alt_L (0xcc),  Meta_L (0xcd)
mod2        Num_Lock (0x4d)
mod3        Scroll_Lock (0x4e),  ISO_Level5_Shift (0xcb)
mod4        Super_L (0x85),  Super_R (0x86),  Super_L (0xce),  Hyper_L (0xcf)
mod5        ISO_Level3_Shift (0x5c)
```

**Comment by pentamassiv** [comment]
Can you please check if https://github.com/enigo-rs/enigo/pull/217 fixes the issue for you? It looks like there was a space in the string and that is why it did not work. ScrollLock does nothing on my machine so I am not sure it fixed the issue.

**Comment by Aworldc** [comment]
ok, i'll look in to it soon.

**Comment by Aworldc** [comment]
looks like there's not a new version on crates.io

I'll see if i can work out how to build this myself

**Comment by pentamassiv** [comment]
That is correct. I did not publish a new version yet, because there have been a number of changes and I want to test it a bit more before releasing them. Since you already have some code where the scroll lock was not working, you can just replace `enigo = "0.1.3"` with `enigo = { git = "https://github.com/enigo-rs/enigo", rev = "95e196a3f2120e87dc5da22852ae8fd1c1edb778"}` in your `Cargo.toml` file. Then you can see if the issue was fixed for you. After I published a new version, I recommend using the versions published on crates.io again.

**Comment by Aworldc** [comment]
oh lol i just downloaded zip and did `enigo = { path = "./enigo-main" }`.

**Comment by pentamassiv** [comment]
That works too. There will be a bunch of other newer commits but I don't remember committing any breaking changes *yet* :-)

**Comment by Aworldc** [comment]
Woo it works!

**Comment by pentamassiv** [comment]
Awesome :-)

**Comment by pentamassiv** [comment]
Just a heads up, I will merge some breaking changes to master soon. You probably want to lock the commit or continue using your local copy of the crate until a new version is published. Until then I will rename and move functions around so it will frequently break your builds

**Comment by pentamassiv** [comment]
I just published https://crates.io/crates/enigo/0.2.0-rc1. Feel free to use that instead of pinning the commit. If nobody complains or has any suggestions, I will publish 0.2.0 soon.
