### ISSUE TITLE
Reading key presses

### ISSUE THREAD

**Issue by TomVer99** [enigo-rs/enigo#229]
**Is your feature request related to a problem? Please describe.**
I would like to use this crate for simulating and reading keypresses.

**Describe the solution you'd like**
Id like a function that simply checks if a Key:: is pressed or not.

**Describe alternatives you've considered**
I saw there are already solutions for this, but they seem to mostly require at least 10 lines of code or the winAPI.

**Additional context**
Id like to be able to use it as follows:
```rs
while !enigo.key_pressed(Key::Layout('q')) {
        // Do something
}
```

**Comment by pentamassiv** [comment]
Sorry, but this is currently out of scope of this library. There are many quirks that I still need to fix and improve the support on Linux.

If the library gets to a point where it does not need any changes, I might revisit that decision.

**Comment by TomVer99** [comment]
@pentamassiv I am personally new to Rust, but would you be okay with it if I maybe try to implement it? Or at least try? haha. Then I could just make a PR.

**Comment by pentamassiv** [comment]
I am open to it, but you have to keep in mind that this library works on all platforms. You would have to write the code for Windows, macOS, Linux X11 (and Linux Wayland). It is a lot more to do, than one would think. I spent many hours on this crate already as you can see from the commit history. I would not merge it if I it is not complete

**Comment by TomVer99** [comment]
@pentamassiv the use of wayland rules this feature out as this is out of scope for that crate https://github.com/Smithay/wayland-rs/issues/670.

I will stop working on this feature for enigo.
