### ISSUE TITLE
Is EnigoSettings Unavailable on Windows

### ISSUE THREAD

**Issue by EDKarlsson** [enigo-rs/enigo#240]
**Describe your Question**
So I don't know if this is a bug or not but I figured I would ask first. It seems that the EnigoSettings struct is not available on windows in enigo 0.1.3. Is this a bug or just not available on windows?

**Describe your Goal**
I'm trying to follow along with the examples provided.

**Environment (please complete the following information):**

- OS: Windows 10
- Rust 1.71
- Library Version enigo 0.1.3

**Comment by pentamassiv** [comment]
Yes, that is to be expected. I am continuing to develop enigo. There are upcoming breaking changes and I did not yet publish a new version. That is why the examples don't work with the old version from crates.io. I describe what you can do in this comment here: https://github.com/enigo-rs/enigo/issues/238#issuecomment-1777096893

**Comment by EDKarlsson** [comment]
Awesome thanks!
