### ISSUE TITLE
macOS: Use objc2 instead of objc

### ISSUE THREAD

**Issue by pentamassiv** [enigo-rs/enigo#249]
The `objc` seems to no longer be maintained and `objc2` is a good replacement. Many larger projects already use it, as can be seen in the list of dependents.

https://crates.io/crates/objc2

**Comment by pentamassiv** [comment]
@paulora2405, maybe you can also do this while you are touching the macOS code?

**Comment by paulora2405** [comment]
Seems easy enough to replace, will try to close this as soon as I can.

What is the proper way of validating any changes like these?

**Comment by pentamassiv** [comment]
If I make some bigger changes, I just manually test the various functions of the `Keyboard` and `Mouse` traits. Theoretically there are some tests, but there are not enough and they are not written well. They use the browser to detect key presses and mouse movements. I always wanted to improve that but did not get to it yet.

For dependency updates I usually assume "If it builds, it works". Probably not ideal though.
