### ISSUE TITLE
Selecting text isn't working

### ISSUE THREAD

**Issue by TeamDman** [enigo-rs/enigo#258]
**Describe the bug**
It should be possible to send Ctrl+Shift+RightArrow to select the word to the right of the cursor.

The cursor moves an entire word, but the text is not selected.

https://github.com/enigo-rs/enigo/assets/9356891/6387dc2a-2d98-45a0-8ffa-8967b873abec

**To Reproduce**
```rust

#[cfg(test)]
mod tests {
    // test that sending shift + arrow keys is highlighting text
    #[test]
    fn test_shift_arrow() {
        use std::thread::sleep;
        use std::time::Duration;
        use enigo::*;
        let mut enigo = Enigo::new();
        sleep(Duration::from_secs(3));
        enigo.key_down(Key::Shift);
        enigo.key_down(Key::Control);
        sleep(Duration::from_secs(1));
        enigo.key_down(Key::RightArrow);
        sleep(Duration::from_secs(1));
        enigo.key_up(Key::RightArrow);
        enigo.key_up(Key::Shift);
        enigo.key_up(Key::Control);
    }
}
```

**Expected behavior**
A word should be selected

**Environment (please complete the following information):**

- OS: Windows 10
- Rust: v1.74.1
- Library Version: v0.1.3

**Comment by TeamDman** [comment]
I think the problem is in the key_down for RightArrow since if I have enigo do key_down for Shift then physically hit right arrow it works, so my guess is that the shift key isn't being included in the scancode for the arrow key

**Comment by pentamassiv** [comment]
Hi, thank you for using my library and taking the time to open the report. I have worked on enigo a lot since version `0.1.3` and fixed many issues ([Changelog](https://github.com/enigo-rs/enigo/blob/main/CHANGES.md)). I did not get to releasing a new version yet. I tried to replicate the described problem in the current master branch and everything worked as expected. There are two release candidates published on crates.io. I have not tried it with them, but they should work as expected too. In order to use the most recent one, add this to your `Cargo.toml` file: `enigo = "0.2.0-rc2"`. The API changed a little bit. Here is the code that worked for me:


```Rust
#[cfg(test)]
mod tests {
    // test that sending shift + arrow keys is highlighting text
    #[test]
    fn test_shift_arrow() {
        use crate::{
            Direction::{Press, Release},
            Enigo, Key, Keyboard, Settings,
        };
        use std::thread::sleep;
        use std::time::Duration;

        let mut enigo = Enigo::new(&Settings::default()).unwrap();

        sleep(Duration::from_secs(1));
        enigo.key(Key::Shift, Press).unwrap();
        enigo.key(Key::Control, Press).unwrap();
        enigo.key(Key::RightArrow, Press).unwrap();

        enigo.key(Key::RightArrow, Release).unwrap();
        enigo.key(Key::Control, Release).unwrap();
        enigo.key(Key::Shift, Release).unwrap();
    }
}
```


 Let me know if that fixes the issue for you too.

**Comment by TeamDman** [comment]
Confirmed, using `0.2.0-rc2` has fixed the issue.

Thank you for your work!

I'm using this with Bevy, so I also had to make sure I'm storing the Enigo instance in a local to ensure that state was preserved, otherwise it would continue to forget about shift being held

```rust

fn handle_input(
    tool_query: Query<&ActionState<KeyboardToolAction>, With<ActiveTool>>,
    mut enigo: Local<Option<Enigo>>,
) {
    if enigo.is_none() {
        *enigo = Enigo::new(&Settings::default()).ok();
    }
    let Some(ref mut enigo) = *enigo else {
        warn!("Failed to create enigo");
        return;
    };

    for tool_actions in tool_query.iter() {
        for variant in KeyboardToolAction::variants() {
            if tool_actions.just_pressed(variant) {
                info!("{:?} key down", variant);
                if let Err(e) = enigo.key(variant.to_enigo(), Press) {
                    warn!("Failed to send key: {:?}", e);
                }
            }
            if tool_actions.just_released(variant) {
                info!("{:?} key up", variant);
                if let Err(e) = enigo.key(variant.to_enigo(), Release) {
                    warn!("Failed to send key: {:?}", e);
                }
            }
        }
    }
}
```
