### ISSUE TITLE
Support BSDs

### ISSUE THREAD

**Issue by syobocat** [enigo-rs/enigo#268]
I believe that this crate works fine on *BSDs, as long as they use the same window system(X11/Wayland) as Linux.

Some functions (like multimedia keys) might not work, but I think most features works fine by just replacing `#[cfg(target_os = "linux")]` with `#[cfg(all(unix, not(target_os = "macos")))]` or something like that.

At least, doing so allowed me to use this crate(v0.2.0-rc2) to simulate a left mouse click on FreeBSD.

**Comment by pentamassiv** [comment]
Thank you for letting me know. I'll make the change within the next few days :-)

**Comment by pentamassiv** [comment]
I forgot about this issue. Sorry about that. Could you test the main branch to see if your issue is resolved?

**Comment by syobocat** [comment]
I have confirmed that both keyboard and mouse input simulation works on FreeBSD.

Thank you!

**Comment by pentamassiv** [comment]
Great, thank you for confirming it
