### ISSUE TITLE
Interior mutability  

### ISSUE THREAD

**Issue by pythoneer** [enigo-rs/enigo#27]
use interior mutability to alter internal fields. It is un-ergonomic to bind Enigo mutably.

**Comment by legolord208** [comment]
Why? If the user doesn't know it's mutable, race conditions might occur, I don't know.

**Comment by pythoneer** [comment]
For now the only mutable fields are the x,y position to track the mouse for relative movement. it is not necessary for all platforms (idk if it is necessary at all) but its not really obvious that "relative" mouse movement is changing internal state and "why" enigo needs a mutable bind. So the idea was to change to interior mutability and hide that "problem" ... i think there is a way to just query the current mouse position anyway and to get rid of that implementation detail. The problem is, changing that is a breaking change that i want to avoid. In my mind enigo should be bound immutable on a regular basis. 

And yes i haven't really put much thought into the use of enigo in a multi threaded environment.

**Comment by jD91mZM2** [comment]
Wait what, you track the mouse movement? When does it update? On some event, or when you call a function? If the latter, doesn't this mean the position will be outdated if the user moves the mouse?

**Comment by pythoneer** [comment]
IDK if we still need this anymore.

**Comment by pentamassiv** [comment]
I think it is fine to require Enigo to be mutable. There haven't been many people complain about it so I am closing this for now. Feel free to reopen it if you feel like it is needed
