### ISSUE TITLE
Doesn't work as expected in simulation “Ctrl+C"

### ISSUE THREAD

**Issue by 7lon7** [enigo-rs/enigo#288]
**Describe the bug**
I would like to implement a function that simulates the ctrl+c keystroke to copy text when the mouse selects the text, and then get the text content from the clipboard. But every time I get the content from the clipboard is the last copied content. And it causes some system functions to be unavailable, for example, when I open two or more chrome, I can't select one of them from the taskbar with the mouse.

**To Reproduce**
```rust
fn mouse_left_button_release() {
    println!("left mouse button is raised");

    let mut enigo = Enigo::new(&Settings::default()).unwrap();
    enigo.key(Key::Control, Press).unwrap();
    enigo.key(Key::Unicode('c'), Click).unwrap();
    enigo.key(Key::Control, Release).unwrap();
    
    let mut clipboard = arboard::Clipboard::new().unwrap();
    println!("Clipboard text was: {}", clipboard.get_text().unwrap());
}
```

**Expected behavior**
Get the text selected by the mouse at this time

**Environment (please complete the following information):**

- OS: Windows10
- Rust 1.78
- Library Version enigo 0.2

**Comment by hxj0x** [comment]
add ` thread::sleep(Duration::from_secs(2));` before get clipboard text，is work for me.
```rust
fn mouse_left_button_release() {
    println!("left mouse button is raised");

    let mut enigo = Enigo::new(&Settings::default()).unwrap();
    enigo.key(Key::Control, Press).unwrap();
    enigo.key(Key::Unicode('c'), Click).unwrap();
    enigo.key(Key::Control, Release).unwrap();

    thread::sleep(Duration::from_secs(2));
    
    let mut clipboard = arboard::Clipboard::new().unwrap();
    println!("Clipboard text was: {}", clipboard.get_text().unwrap());
}
````

**Comment by pentamassiv** [comment]
Thank you @hxj0x for helping with this issue. I am surprised a sleep is needed. Enigo used sleep in the past but no longer needs sleep in its code and everything gets simulated intantly. I don't think there is anything that can be done on our side so that the sleep is no longer needed.
