### ISSUE TITLE
Screenshot under window does not work

### ISSUE THREAD

**Issue by han1548772930** [enigo-rs/enigo#289]
fn main() {
    let mut enigo = Enigo::new(&Default::default()).unwrap();

    enigo.key(Key::LWin, Press).unwrap();
    enigo.key(Key::Print, Click).unwrap();
    
}

**Comment by pentamassiv** [comment]
Thank you for your bug report. When looking into it, I discovered that the `Key::Print `has the wrong virtual key associated with it. I created a [PR ](https://github.com/enigo-rs/enigo/pull/294) to adress this and will merge it within the next couple of days. Once it is merged, you can just use `Key::Print`. Until then you unfortunately have to use `Key::Snapshot `on Windows and `Key::Print `on Linux and BSD. Sorry about that.
