### ISSUE TITLE
In Windows 10, `enigo.text()` doesn't work with newline character 

### ISSUE THREAD

**Issue by NathanMBR** [enigo-rs/enigo#303]
**Describe the bug**
The `enigo.text()` function doesn't correctly handle text that contains a newline character (`\n`). No matter how many newline characters are in the text, it writes only one, and other characters are omitted.

**To Reproduce**
Open the Windows Notepad, run the code bellow and click at the notepad:
```rs
use enigo::{Enigo, Keyboard, Settings};
use std::thread;
use std::time::Duration;

fn write(text: String) {
    let mut enigo = Enigo::new(&Settings::default()).unwrap();
	
    enigo.text(&text).unwrap();
}

fn main() {
    println!("Executing write...");
	
    thread::sleep(Duration::from_secs(5));
	
    write(String::from("Test \nwith \nlots \nof \nnewlines"));
}

```

The `thread::sleep()` call isn't related with the issue - it's just a way to have time to click on Windows Notepad, so that the content can be written.

**Expected behavior**
The text should be written in the following way:
```text
Test
with
lots
of
newlines
```

**Environment**

- OS: Windows 10
- Rust version: 1.78.0
- Library Version: enigo 0.2.1

**Additional context**
Tested on native and emulated Windows instances, and both demonstrated this issue.

**Comment by pentamassiv** [comment]
Thank you for letting me know. I'll fix it within the next week and publish a new version. Feel free to ping me if I forgot :-)

**Comment by pentamassiv** [comment]
Wow, thank you for the investigation. That makes a lot of sense. I've been working on the macOS code and didn't get to this issue yet. You made it much easier for me to fix it 👍
