### ISSUE TITLE
Does enigo support mouse drag event?

### ISSUE THREAD

**Issue by qzd1989** [enigo-rs/enigo#316]
**Describe your Question**
In the examples, I only saw mouse events:  move_mouse, scroll, button(Press, Release, Click)

**Describe your Goal**
Will enigo support it?

**Environment (please complete the following information):**

- OS: [macOS ..]
- Rust [rustc 1.82.0-nightly (13a52890d 2024-08-14)]
- Library Version [enigo = "0.2.1"]

**Comment by pentamassiv** [comment]
You can click, move the mouse and then release it. You can use that to drag the mouse. Or do you mean something else?
