### ISSUE TITLE
Support more buttons in DSL

### ISSUE THREAD

**Issue by pythoneer** [enigo-rs/enigo#34]
The DSL has a limited amount of buttons that it currently supports. In the first iteration i think its a good idea to support all layout independent ones.

**Comment by legolord208** [comment]
Should be possible by just adding some more `match` cases to the parser.rs file :+1:

**Comment by pythoneer** [comment]
I am confident to find some time this week to do so.

**Comment by BrettMayson** [comment]
Some more added in #134
