### ISSUE TITLE
[windows10]program hangs when releasing the key.

### ISSUE THREAD

**Issue by Mia-Zhang-Forever** [enigo-rs/enigo#342]
**Describe the bug**
program hangs when releasing the key.

**To Reproduce**
code: https://github.com/jasonjmcghee/plock
how to build:
```
pnpm install
pnpm tauri dev
```
The shortcut is bound with `Ctrl+Shift+.`. This shortcut will copy the current text selection. During the copy process, the Ctrl key is released, and the program is just hanging there.

here is the log:
```
[2024-10-27][00:10:21][DEBUG][enigo] using default settings
[2024-10-27][00:10:21][DEBUG][enigo::platform::win_impl] connection established on windows
[2024-10-27][00:10:21][DEBUG][enigo::platform::win_impl] key(key: Control, direction: Release)
[2024-10-27][00:10:21][TRACE][enigo::keycodes] Key::try_from(key: Control)
[2024-10-27][00:10:21][TRACE][enigo::keycodes] virtual key: VIRTUAL_KEY(17))
```
when I try to invoke the shortcut again, it does nothing (the log is hung here , it works as expected on macOS)

**Expected behavior**

**Environment (please complete the following information):**

- OS: windows10
- Rust: 1.8.2
- lastest commit (tried several commits, none is working)

**Comment by Mia-Zhang-Forever** [comment]
it seems that the process hangs at :
```rust
    if unsafe { SendInput(input, input_size) } == input_len {
        Ok(())
    } else {
        let last_err = std::io::Error::last_os_error();
        error!("{last_err}");
        Err(InputError::Simulate(
            "not all input events were sent. they may have been blocked by UIPI",
        ))
    }
  ```
  
<img width="795" alt="image" src="https://github.com/user-attachments/assets/e217c21a-58b2-454b-b67e-c5a27b0ae7d5">

Do you have any ideas on how to fix it on Windows 10?

<img width="658" alt="image" src="https://github.com/user-attachments/assets/20afc234-3a18-41b9-bcb0-bc13fff59e47">

**Comment by pentamassiv** [comment]
Unfortunately I don't have an idea right now. I did't think it could hang at all :S

**Comment by Mia-Zhang-Forever** [comment]
> Unfortunately I don't have an idea right now. I did't think it could hang at all :S
thanks for the reply, it might not be the issue of enigo, I will close this one.
