### ISSUE TITLE
enigo.key triggers panic and bug out the Tauri app in latest Mac OS

### ISSUE THREAD

**Issue by grandwaterman** [enigo-rs/enigo#352]
**Describe the bug**
Wherever enigo.key fn is used, it panics and bugs out the app in Tauri
but mouse actions are fine.

**To Reproduce**
Steps or a minimal code example to reproduce the behavior.
Here is an example where key fn is used, but it applies to other places where key fn is used too such as click/pressdown/release a key.
```rs
#[tauri::command]
async fn key_press(key: char) -> Result<(), String> {
    let mut enigo = Enigo::new(&Settings::default()).map_err(|e| e.to_string())?;
    enigo.key(Key::Unicode(key), Click).map_err(|e| e.to_string())?;
    Ok(())
}
```

**Expected behavior**
It was functioning properly before the lastest Mac OS update.

**Environment (please complete the following information):**

- OS: [e.g. Linux, Windows, macOS ..]. MacOS Sequoia 15.1
- Rust [e.g. rustc --version]   rustc 1.81.0
- Library Version [e.g. enigo 0.0.13 or commit hash fa448be ]. enigo = "0.2.1"

**Additional context**

Here is part of the Mac error report, per GPT while digging it, seems there is a race condition
Crashed Thread:        10  tokio-runtime-worker

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x000000018ba92a60

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [5051]

The error report indicates a crash in a Tauri app using the enigo crate for keyboard input automation on macOS. Specifically, the crash is related to macOS's input source handling and likely stems from improper or unsafe usage of the macOS APIs related to keyboard input or keycode mappings.

Breakdown of the Issue:
Assertion Failure: The key failure appears at libdispatch.dylib, involving an assertion failure (_dispatch_assert_queue_fail), which means the code is being run on the wrong thread or queue.
HIToolbox Library: The crash report involves islGetInputSourceListWithAdditions and TSMGetInputSourceProperty, functions related to macOS's text input management.
enigo Crate Call: The error occurs when enigo tries to create a string for a key or maps a keycode using macOS-specific implementations (create_string_for_key and keycode_to_string).

**Comment by pentamassiv** [comment]
Thank you for investigating it. I don't know why Tauri crashes for some people but not for others. There already is a similar [issue](https://github.com/enigo-rs/enigo/issues/153), but it seems like the crash happens at a different part of the code for you. Towards the end of that issue, I wrote down some [instructions](https://github.com/enigo-rs/enigo/issues/153#issuecomment-2442090821) to run a test Tauri app. Could you please check if you experience any crashes with it?

You mentioned that it previously worked for you. Which version of macOS did you use before?

**Comment by pentamassiv** [comment]
I just noticed that you are using enigo in an async function. I never tested enigo in an async function, so that could be a reason why it crashes. I guess you do that because enigo used to require sleeps on macOS and took a few miliseconds to finish?

I recently was able to get rid of the sleeps so it should not be needed. Could you please remove the async keyword and change your dependency in the `Cargo.toml` file to:
`
enigo = { git = "https://github.com/enigo-rs/enigo", branch = "main" }
`

**Comment by grandwaterman** [comment]
I started a few testing file and seems it works somehow, I will do more check and test. thanks for the responses.

**Comment by pentamassiv** [comment]
Can you please tell me what you changed for it to work? That will help other users

**Comment by grandwaterman** [comment]
Yes, just followed your suggestions, removed async and changed crate config.

**Comment by pentamassiv** [comment]
I wonder if the keyboard.rs example would also panic if you changed it to execute async.

Unfortunately I am busy for the next days/weeks and will have very little time to investigate. I'd review a pull request though if you find a fix

**Comment by grandwaterman** [comment]
Thanks, after more checking and digging, here are what I found:
1. Problems do occure on async fn only, if I change any keyboard fn to async, I experience this bug and the app crashes.
2. Per GPT, this is the comment below, I guess when users try to use async, the program assigns the task to tokio-runtime-worker instead of keeping them on the main thread, which is not allowed in Mac OS and causes the app crash.
The issue appears to be related to macOS's HIToolbox (Human Interface Toolbox) operations not being executed on the main thread. In macOS, certain UI operations must be performed on the main thread, but your code is trying to execute them in a tokio worker thread.

**Comment by pentamassiv** [comment]
Okay, thank you for looking into it. I think enigo can run on other threads too though. I remember testing that not to long ago. I just spawned a new thread and I'm that new thread I executed it.

Is it okay with you if I close the issue? I don't see how I can make any changes to prevent this

**Comment by grandwaterman** [comment]
Thanks, so what is the recommondation here if I need to execute async funtions, it seems not only async fn for enigo causes the crash, any other async fn causes crashes too.

**Comment by grandwaterman** [comment]
Closing the issue, thanks for the help.

**Comment by pentamassiv** [comment]
My advice for now would be to avoid calling it in an async function until I found the reason why it panics and can prevent that.

I never used async before so I'm not familiar with it. Maybe there are ways you can execute code synchronously within an async block?

**Comment by grandwaterman** [comment]
The interesting part is mouse actions work well in both cases.How do you normally carry out activities that need to be waited without async fn? On Nov 2, 2024, at 6:53 PM, pentamassiv ***@***.***> wrote:﻿
My advice for now would be to avoid calling it in an async function until I found the reason why it panics and can prevent that.
I never used async before so I'm not familiar with it. Maybe there are ways you can execute code synchronously within an async block?

**Comment by StephanieTM** [comment]
I'm new to both Rust and Tauri, and I've encountered this issue as well.
The code below works for me after discussing with ChatGPT based on your conversation above:
```
    async fn some_async_fn(app: &AppHandle) {
        // ... async logics

        let _ = app.run_on_main_thread(move || {
            let mut enigo = Enigo::new(&Settings::default()).unwrap();
            enigo.key(Key::Meta, Press).unwrap();
            enigo.key(Key::Unicode('c'), Click).unwrap();
            enigo.key(Key::Meta, Release).unwrap();
        });
    }
```

Hope it won't introduce any other issues.
