### ISSUE TITLE
Better guidance on usage on MacOS

### ISSUE THREAD

**Issue by JakkuSakura** [enigo-rs/enigo#357]
**Describe the bug**
I wanted to use this for my school project, but I was disappointed.

1. relative mouse movement does not work
2. failed to compile with simple keys
```rust
error[E0599]: no variant or associated item named `A` found for enum `enigo::Key` in the current scope
  --> src/main.rs:16:25
   |
   |         device.key(Key::A, Direction::Click)?;
   |                         ^ variant or associated item not found in `enigo::Key`

```
**To Reproduce**
```rust
use enigo::{Direction, Key, Keyboard, Mouse, Settings};
use eyre::Result;
fn main() -> Result<()> {
    let mut device = enigo::Enigo::new(&Settings::default())?;
    loop {
        device.move_mouse(0, 10, Coordinate::Rel)?; // no effect
        device.key(Key::A, Direction::Click)?; // failed to compile
    }
}
```

**Expected behavior**
It's trivial that these keys should work. At least put the status of Linux and MacOS on 

**Environment (please complete the following information):**

- OS: macOS
- Rust rustc 1.81.0-nightly (6868c831a 2024-06-30)
- Library Version egino 0.2.1

**Additional context**
I tried pyautogui and it's working as expected

**Comment by JakkuSakura** [comment]
for 1, figured out I need to enable Accessibility for my IDE
<img width="473" alt="image" src="https://github.com/user-attachments/assets/12dc44df-9861-44f1-83ca-298b24ce9258">
then it should work

**Comment by JakkuSakura** [comment]
On MacOS, Key::A does not exist; rather, I need to use Key::Unicode('a'). This should be documented more clearly

**Comment by pentamassiv** [comment]
It's all documented: 
- https://docs.rs/enigo/latest/enigo/enum.Key.html
- https://github.com/enigo-rs/enigo?tab=readme-ov-file#permissions

**Comment by pentamassiv** [comment]
That's also what the examples are for: 
https://github.com/enigo-rs/enigo/blob/main/examples/keyboard.rs
