### ISSUE TITLE
Umlauts not working

### ISSUE THREAD

**Issue by pythoneer** [enigo-rs/enigo#36]
```rust
extern crate enigo;
use enigo::{Enigo, KeyboardControllable, Key};
use std::thread;
use std::time::Duration;

fn main() {
    thread::sleep(Duration::from_secs(2));
    let mut enigo = Enigo::new();

    enigo.key_click(Key::Layout("ä".into()));
}
```

**Comment by legolord208** [comment]
To solve this, either you use it as unicode, or we specify a `Key::` for it... Correct?

**Comment by pythoneer** [comment]
Not entirely sure what i meant by this – this should remind me to write better and more elaborate issues – but i think this was fixed by https://github.com/enigo-rs/enigo/pull/42 .. either way it is working now on master.
