### ISSUE TITLE
Mouse coordinate system in Windows is not scaled

### ISSUE THREAD

**Issue by TTsdzb** [enigo-rs/enigo#370]
**Describe the bug**
When setting a scale (125%, for example) for the display, coordinate system on Windows becomes inconsistent with other platforms. The size of the screen becomes the size before scaling, while on other platforms it gets the actual physical size.

To click on the proper position, I have to divide the actual point with the scale factor on Windows.

```rs
fn click(&mut self, pos: &Point) -> Result<(), InputError> {
    debug!("Clicking at ({}, {})", pos.x, pos.y);

    #[cfg(target_os = "windows")]
    let (x, y) = (
        (pos.x as f32 / self.scale_factor) as i32,
        (pos.y as f32 / self.scale_factor) as i32,
    );
    #[cfg(not(target_os = "windows"))]
    let (x, y) = (pos.x as i32, pos.y as i32);

    self.enigo.move_mouse(x, y, enigo::Coordinate::Abs)?;
    self.enigo
        .button(enigo::Button::Left, enigo::Direction::Click)?;

    Ok(())
}
```

**To Reproduce**
```rs
let mut enigo = Enigo::new(&enigo::Settings::default()).unwrap();
let size = self.enigo.main_display().unwrap();
println!("{}x{}", size.0, size.1);
```

On a 1080P, Windows 11 PC with 125% scaling, it produces the output below:

```
1536x864
```

However the same code on the same PC with KDE Plasma (Wayland) and the same setting:

```
1920x1080
```

**Expected behavior**
Coordinates in Windows should be the physical one, like other platforms.

**Environment (please complete the following information):**

- OS: Windows 11 23H2
- rustc 1.83.0 (90b35a623 2024-11-26)
- enigo = { version = "0.3.0", features = ["wayland"] }

**Comment by pentamassiv** [comment]
I created a [PR](https://github.com/enigo-rs/enigo/pull/374) to fix this. There's actually not much enigo can do to make this work. Please look at the PR and the newly added documentation within it for more details.
