### ISSUE TITLE
Fetch peripherals data from system

### ISSUE THREAD

**Issue by pythoneer** [enigo-rs/enigo#44]
use data about the system like (screen size, number of connected monitors, mouse position etc) and make it accessible through public API. Possibly API changes for eg. moving the mouse to let the user choose the monitor.

should solve issues    https://github.com/enigo-rs/enigo/issues/40 https://github.com/enigo-rs/enigo/issues/27 https://github.com/enigo-rs/enigo/issues/26

**Comment by spacekookie** [comment]
Via `libxdo_sys::xdo_get_mouse_location` (on Linux) it's possible to get the current mouse position. 

What I think would be awesome if enigo could abstract away monitor setups somehow and handle the available area as a single coordinate system (at least optionally)

**Comment by pentamassiv** [comment]
Done, there only is an issue with multiple monitors: https://github.com/enigo-rs/enigo/issues/155
