### ISSUE TITLE
Is it possible to send keystrokes to an inactive application?

### ISSUE THREAD

**Issue by neatacct** [enigo-rs/enigo#48]
Is it possible to send keystrokes to an inactive application? It's unclear to me from the documentation..

**Comment by jD91mZM2** [comment]
It's not, but it certainly should be! This is yet another issue where we'd love optional arguments to the API to not make it too messy.

**Comment by pythoneer** [comment]
It is unclear to me if this is possible in a cross platform fashion. I think it's possible to do that on Linux currently have no idea what the Mac/Win side should look like. I think we need to figure out how to enumerate the windows for a user facing cross platform way.

**Comment by neatacct** [comment]
Do you know someone that would be willing to take a bounty to look into this? I need it for Windows and I need it badly, haha.

**Comment by neatacct** [comment]
Looking to drop something like 100 US to get this started.

**Comment by pythoneer** [comment]
I don't really know what to do with this issue. I tend to feel like it is out of scope for this crate. I think such specific behavior should be handwritten for the specific platform. If we ever wanted this, we would need a way for this to work on all supported platforms and have a "general" way to "choose" an application those events are directed to. I feel like enigo is supposed to work in such a way a "normal" user can interact with a system and not to bypass common system behavior. I am certainly not against someone making a PR for that in the future – but currently i don't think that investigating this further from my side is worth the effort in the current stage of the library.
