### ISSUE TITLE
Add basic derived Traits where possible to the enigo data structures

### ISSUE THREAD

**Issue by najamelan** [enigo-rs/enigo#53]
I found myself wanting to create a struct which held a field of type enigo::Key, so it could pass this every time it has to call an enigo function like `key_up`. Unfortunately methods like this one take ownership of the key that one sends in (which is probably a bad idea in itself), and the enum does not derive "Copy, Clone" or other basic traits, and Copy no longer is implicit nowadays. 

Practically this means that a user has to hard code which key they want to send and can't store it in a variable, since it can't be copied...

I kind of didn't find any way to work around this except modifying enigo. I will make a pull request for enigo::Key, but other data structures might be affected as well.

**Comment by jD91mZM2** [comment]
This is a good idea, thanks for the PR!
