### ISSUE TITLE
Linux doesn't press any non-alphanumeric keys

### ISSUE THREAD

**Issue by Hand-of-Cthulhu** [enigo-rs/enigo#56]
If you send any non-alphanumeric key, enigo seems to just send it directly to xdotool, which it doesn't accept. (it just gives the error `Error: Invalid key sequence '.'` or `Failure converting key sequence '.' to keycodes`).
List of keys affected: 
```
`
-
=
[
]
\
;
'
,
.
/
```
I think I can make a PR to fix this.

**Comment by jD91mZM2** [comment]
Works perfectly for me. What's your version of xdotool?

**Comment by Hand-of-Cthulhu** [comment]
xdotool version 3.20160805.1

**Comment by jD91mZM2** [comment]
Edited my reply, noticed that it didn't work with some functions

**Comment by Hand-of-Cthulhu** [comment]
I'm using key_down and key_up. I just checked key_sequence, and that works fine.

**Comment by jD91mZM2** [comment]
Alright. I have no idea how to fix this, so I'm looking forward to the PR :)
