### ISSUE TITLE
Space (0x20) is an 'Invalid key sequence'

### ISSUE THREAD

**Issue by vandenoever** [enigo-rs/enigo#62]
This program on Linux with X11 with xdotool-3.20160805.1 and enigo 0.0.12 gives an error:
```rust
    let mut enigo = Enigo::new();
    enigo.key_sequence_parse(" ");
```
```
Error: Invalid key sequence ' '
Failure converting key sequence ' ' to keycodes
Error: Invalid key sequence ' '
Failure converting key sequence ' ' to keycodes
```

**Comment by pythoneer** [comment]
Thanks for the report. I'll look into that!

**Comment by pythoneer** [comment]
Does the problem still exists? I cannot reproduce this on ArchLinux with xdotool-3.20160805.1-2 and enigo master.
