### ISSUE TITLE
Cross platform mouse position and display size 

### ISSUE THREAD

**Issue by pythoneer** [enigo-rs/enigo#74]
We already have implementations for [win](https://github.com/enigo-rs/enigo/blob/949da7042904921530d27a19ebcb2e7bb3615839/src/win/win_impl.rs#L159) and [mac](https://github.com/enigo-rs/enigo/blob/949da7042904921530d27a19ebcb2e7bb3615839/src/macos/macos_impl.rs#L410) so we just need one for Linux and are good to go and can implement it on the "general" [Enigo struct](https://github.com/enigo-rs/enigo/blob/949da7042904921530d27a19ebcb2e7bb3615839/src/lib.rs#L380) or on the [Mouse Trait](https://github.com/enigo-rs/enigo/blob/949da7042904921530d27a19ebcb2e7bb3615839/src/lib.rs#L115) but i am unsure if that is the right place for the display size? 

- [x] Linux impl
- [ ] Cross Platform impl

**Comment by pentamassiv** [comment]
Done
