### ISSUE TITLE
Use main_display_size in mouse_move_to

### ISSUE THREAD

**Issue by pythoneer** [enigo-rs/enigo#75]
Instead of the "magic" implementation of getting the screen dimensions in [mouse_move_to](https://github.com/enigo-rs/enigo/blob/949da7042904921530d27a19ebcb2e7bb3615839/src/win/win_impl.rs#L53) use the newly added [main_display_size](https://github.com/enigo-rs/enigo/blob/949da7042904921530d27a19ebcb2e7bb3615839/src/win/win_impl.rs#L159) for its implementation – no one knows what `GetSystemMetrics(78)` means.

**Comment by pentamassiv** [comment]
By now the implementation is even more confusing. Now it is:
```rust
    fn mouse_move_to(&mut self, x: i32, y: i32) {
        mouse_event(
            MOUSEEVENTF_MOVE | MOUSEEVENTF_ABSOLUTE | MOUSEEVENTF_VIRTUALDESK,
            0,
            (x - unsafe { GetSystemMetrics(SM_XVIRTUALSCREEN) }) * 65535
                / unsafe { GetSystemMetrics(SM_CXVIRTUALSCREEN) },
            (y - unsafe { GetSystemMetrics(SM_YVIRTUALSCREEN) }) * 65535
                / unsafe { GetSystemMetrics(SM_CYVIRTUALSCREEN) },
        );
    }
```
Do you remember why it was changed to this and can you explain it?
