### ISSUE TITLE
Read the cursor position and the color of the position?

### ISSUE THREAD

**Issue by mantou132** [enigo-rs/enigo#77]

**Comment by pythoneer** [comment]
What is your specific use case for this?

**Comment by mantou132** [comment]
@pythoneer https://github.com/mantou132/GoogleTranslate

Need to check the text of the translation cursor position when pressing the shortcut key

**Comment by pythoneer** [comment]
Its unclear to me how you want to achieve this? If you get a mouse position for like (500, 400) and an RGB value for that particular pixel (133,13,255) you can't really check anything, can you?

I have though about such a feature where you get a rectangle of the screen and check – with computer vision – if the pixels are roughly the same. For things like "finding GUI elements" like buttons are check if a button click was successful. But i am unsure if this crate is the right scope for such a feature. Maybe something like a `enigo-helper` crate would be a solution where you could have something like "recording", "image-asserts" or "waiting" that a GUI element appears "based on image comparison".

But i don't see the value in getting a single Pixel at the current mouse location?

**Comment by mantou132** [comment]
If the user can provide a rectangle, then the pixels in the rectangle can be read and the text recognized using OCR type technology.

These features really should not be provided by enigo.

i will close issue

thx
