### ISSUE TITLE
How to work in neon?

### ISSUE THREAD

**Issue by mantou132** [enigo-rs/enigo#80]
I am going to build a nodejs binding.  https://github.com/mantou132/enigojs/blob/master/native/src/lib.rs

but I will encounter some errors:
```
Segmentation fault: 11
```
```
node(49766,0x10d11b5c0) malloc: *** error for object 0x10251bb10: pointer being freed was not allocated
node(49766,0x10d11b5c0) malloc: *** set a breakpoint in malloc_error_break to debug
```
Uncertain where the problem comes from. https://github.com/neon-bindings/neon/issues/465

thx

**Comment by pythoneer** [comment]
I am not familiar with nodejs/neon in that regard. Is it by just instantiating `enigo` or using a particular function? What OS is this running on and have you tried it on other Operating Systems?

**Comment by farism** [comment]
@mantou132 I was playing with an electron + neon + enigo project the other day, you can see the work here

https://github.com/farism/autohex/tree/master/packages/node-enigo

Might be worth trying to publish this?

**Comment by mantou132** [comment]
@farism this repo has taught me a lot of knowledge, thank you.
I need to use enigo in my electron project, so I hope you can publish it. recommend using a camel style api.

But there is still a problem that has not been resolved. Why does the following code call an error in nodejs?
```rust
fn key_sequence_parse(mut cx: FunctionContext) -> JsResult<JsUndefined> {
    let s = cx.argument::<JsString>(0)?.value();
    let mut enigo = Enigo::new();
    enigo.key_sequence_parse(&s);
    Ok(cx.undefined())
}
register_module!(mut cx, {
    cx.export_function("keySequenceParse", key_sequence_parse)
});
```

@farism @pythoneer node-enigo can move to the enigo-rs organization and organization rename?
```
├── enigo
│   ├── enigo-rs
│   ├── node-enigo
│   ├── ... other
```

**Comment by mantou132** [comment]
@farism I try to use `export_class`, but the same mistake occurred

https://github.com/mantou132/enigojs/blob/master/native/src/lib.rs

```bash
$ node -v
v12.3.1
```
os: macOS 10.14.5

**Comment by pentamassiv** [comment]
This seems out of scope so I am closing it. If there are any changes needed, please open a new ticket.
