### ISSUE TITLE
Enable MIRI with CI

### ISSUE THREAD

**Issue by pythoneer** [enigo-rs/enigo#81]
Try to enable MIRI – take a look here

https://www.reddit.com/r/rust/comments/e1az07/fyi_if_you_have_a_crate_that_involves_a_lot_of/

**Comment by pentamassiv** [comment]
Done in 820e549742a22342ad5035ccd1290cd3a95a78a9

It did not complain about anything (yet) but it only addes ~2 min to the time the Github Workflow runs, so I think that is acceptable
