### ISSUE TITLE
something wrong with  "arrow key"

### ISSUE THREAD

**Issue by dbsxdbsx** [enigo-rs/enigo#84]
The following  code gives result out of expectation in win10.
```
    // enigo.key_down(Key::Raw(0x27));
    // thread::sleep(Duration::from_secs(1));
    // enigo.key_up(Key::Raw(0x27));
    //
    enigo.key_down(Key::RightArrow);
    thread::sleep(Duration::from_secs(1));
    enigo.key_up(Key::RightArrow);
```
One guess is that  there are missing code for "expanded key data" when keys  are "left, right, up and down". The code for these keys is a little different.

**Comment by pythoneer** [comment]
Hi and thank you for your issue. What do you mean by 
> gives result out of expectation
? What are your expectations?

**Comment by dbsxdbsx** [comment]
@pythoneer, it would output character like "8" or other characters.

**Comment by rukai** [comment]
I have this same issue, arrow keys are outputting the following numbers instead of the expected arrow key:
down: 2
up: 8
left: 4
right: 6

**Comment by mefechoel** [comment]
This is caused by the same issue described in #99. I explained how I worked around it there too, but it's not elegant and you need to configure the build to use it on windows only.

**Comment by pentamassiv** [comment]
Fixed :)
