### ISSUE TITLE
Panics will keep modifiers pressed

### ISSUE THREAD

**Issue by antoyo** [enigo-rs/enigo#95]
**Describe the bug**
If a do a `key_down(Shift)` and then panic, the shift key will be kept pressed.

**To Reproduce**
```rust
use enigo::{Enigo, Key, KeyboardControllable};
use std::thread;
use std::time::Duration;

fn main() {
    thread::sleep(Duration::from_secs(2));
    let mut enigo = Enigo::new();

    enigo.key_down(Key::Shift);
    enigo.key_click(Key::Layout('r'));
    panic!();
    enigo.key_up(Key::Shift);
}
```

Run this and after it panicked, type some text in the terminal on Linux and it should be in capital letters even when not pressing Shift.

**Expected behavior**
I expect the library to somehow clean up the modifiers that where pressed. Not sure if that makes sense or how easy it is to do.

**Environment (please complete the following information):**
 - OS: Linux
 - Rust rustc 1.45.0-nightly (7ebd87a7a 2020-05-08)
 - Library Version 0.0.14

**Additional context**

**Comment by pentamassiv** [comment]
I am not (yet) using enigo but when I wrote a keyboard application, I had the same problem. I solved it by implementing the Drop trait. Maybe you could also do something along the lines of
```
impl Drop for VKService {
    /// If the VKService gets dropped, all keys and modifiers get released to avoid a key getting repeatedly pressed even after the progam ended
    fn drop(&mut self) {
        error!("VKService was dropped");
        if self.release_all_keys_and_modifiers().is_err() {
            error!(
                "Some keys or modifiers could not be released and are still registered as pressed!"
            );
        };
    }
}
```

**Comment by Krysme** [comment]
I believe that the crate `scopeguard` could be used for your case.Actually, clean up code should always be `drop` based to ensure that it runs no matter what.

**Comment by pentamassiv** [comment]
Fixed. All keys are released when the `enigo` struct is dropped.
